version: '3.8'
services:
  express:
    image: hpt_back
    container_name: hetzner_price_tracker_backend
    networks:
      - app_network
    expose:
      - "3000"
    restart: unless-stopped

  discordjs:
    image: hpt_bot
    container_name: hetzner_price_tracker_bot
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge